### ISSUE TITLE
issue with init.taxonerd

### ISSUE THREAD

**Issue by jaum20** [nleguillarme/taxonerd#26]
after installing taxonerd and downloading a model with `install.model(model="en_ner_eco_md_weak", version="1.1.0")` I can't create a taxonerd object:

`taxonerd <- init.taxonerd(model = "en_core_eco_weak_md", gpu=FALSE)
`

```
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'taxonerd'
Run `reticulate::py_last_error()` for details.
```

reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/user/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/user/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
  File "/home/user/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 120, in _hook
    return _find_and_load(name, import_)
ModuleNotFoundError: No module named 'taxonerd'

**Comment by nleguillarme** [comment]
It looks like something went wrong during TaxoNERD installation. Can you send me the code you used to install it?

**Comment by jaum20** [comment]
just as in the readme: 

> install.packages("https://github.com/nleguillarme/taxonerd/releases/download/v1.5.4/taxonerd_for_R_1.5.4.tar.gz", repos=NULL)
